### ISSUE TITLE
Section 5

### ISSUE THREAD

**Issue by gfokkema** [spoofax-shell/doc#23]
Skip Lentz, [29.04.16 21:36]
[Forwarded from Gerlof Fokkema]
ik kan voor problem-analysis nog verzinnen:
- schrijven over environment als stratego term naar file kunnen saven
- wat er gebeurt als je een stuk AST transplanteert waardoor een method ineens invalid return type heeft
- uberhaupt listen van environment is mssn een interessante vraag

Skip Lentz, [29.04.16 21:36]
[Forwarded from Gerlof Fokkema]
want dat betekent dat je vrij diep interpreter internals in moet duiken @ laatste punt

Skip Lentz, [29.04.16 21:37]
1) voor persistent history?
2) misschien is dat geen probleem als static analysis wordt gedaan, kan je error krijgen?
3) ja maybe idd

Gerlof Fokkema, [29.04.16 21:40]
[In reply to Skip Lentz]
1) ja
2) ik denk dat het niet een probleem is, aangezien je de ast kan modifyen en daarna de analyze stap er over heen doet, maar dat is juist het punt, kan je mooi je idee van oplossing beschrijven
3) jente liet net een screenshot zien dat dat ook wel meevalt

Gerlof Fokkema, [29.04.16 21:40]
mbt punt 2: dat is dus extra reden om zelf het hele build proces aan te sturen

Jente Hidskes, [29.04.16 21:42]
- wat er gebeurt als je een stuk AST transplanteert waardoor een method ineens invalid return type heeft

hoe kan dat voorkomen? bij het redefinen van de method zal je dan toch een error krijgen?

Jente Hidskes, [29.04.16 21:43]
voordat je transplanteert is het stukje "donor" AST toch ook getypechecked enzo?

Jente Hidskes, [29.04.16 21:43]
sowieso wordt de hele method geredefined (ookal pas je alleen 1 variable er in aan), dus de hele method wordt getypechecked

Gerlof Fokkema, [29.04.16 21:44]
nee

Gerlof Fokkema, [29.04.16 21:44]
[In reply to Jente Hidskes]
nee

Jente Hidskes, [29.04.16 21:44]
hoe wil je dan je donor ast maken/

Gerlof Fokkema, [29.04.16 21:44]
alleen geparsed

Jente Hidskes, [29.04.16 21:45]
oke dan heb ik de fix: voordat je transplanteert ook eerst typecheken :P

Gerlof Fokkema, [29.04.16 21:45]
class A {
  static int a() {
    return 1;
  }
}
run
  int a = A.a()

---

class A {
  -
}
run
  int a = A.a()

---

class A {
  static long a() {
    return 1;
  }
}
run
  int a = A.a()

Gerlof Fokkema, [29.04.16 21:45]
na transplanten type checken ;p

Gerlof Fokkema, [29.04.16 21:45]
voor transplanten kan juist niet, omdat dat niet een volledig programma is

Jente Hidskes, [29.04.16 21:46]
maar een losse expressie is ook geen volledig programma en moet in de context van een REPL ook worden getypechecked

Gerlof Fokkema, [29.04.16 21:46]
ja, maar dan moet je zoeken waar ergens in de AST die partial expressie geldig is

Gerlof Fokkema, [29.04.16 21:46]
en als je gewoon eerst transplant en daarna het geheel typecheckt :p

Jente Hidskes, [29.04.16 21:46]
true

Gerlof Fokkema, [29.04.16 21:46]
hoef je niet te zoeken :p

Jente Hidskes, [29.04.16 21:47]
maar in het geval van een grote AST is het mooi als we alleen de delta kunnen doen

Jente Hidskes, [29.04.16 21:47]
maar dat is wishful thinking :P

Gerlof Fokkema, [29.04.16 21:47]
very true

Skip Lentz, [29.04.16 21:47]
wat moet er nog gedaan

Jente Hidskes, [29.04.16 21:47]
kunnen we vermelden dat dat nog een mogelijke optimalisatie is

Gerlof Fokkema, [29.04.16 21:47]
das ook een goeie consideration voor section 6

**Comment by Hjdskes** [comment]
The empty headlines have been added to the section, they'll be filled in tomorrow.

**Comment by Hjdskes** [comment]
Closing, see #41.
