### ISSUE TITLE
Research report structure

### ISSUE THREAD

**Issue by gfokkema** [spoofax-shell/doc#3]
# Please add your name to whichever section you choose to write.
## Structure of the report
- [x] [Introduction](https://github.com/spoofax-shell/doc/pull/10) (Gerlof)
- [x] [Spoofax](https://github.com/spoofax-shell/doc/pull/7) (Skip)
  - [x] SDF3 (Syntax definition)
  - [x] NABL (Namespaces)
  - [x] TS (Types)
  - [x] Stratego (Program Transformation)
  - [x] DynSem (Dynamic Semantics)
  - [x] ESV (Editor Services) (#12)
  - [x] Conclusion thingy (#12)
- [x] [Read-Eval-Print Loops](https://github.com/spoofax-shell/doc/pull/9) (Jente)
  - [x] Feature comparison (Jente)
- [x] [Literate Programming](https://github.com/spoofax-shell/doc/pull/14) (Gerlof)
  - [x] What is literate programming?
- [x] [Problem definition](https://github.com/spoofax-shell/doc/pull/11) (Gerlof)
- [x] [Problem analysis](https://github.com/spoofax-shell/doc/pull/15) (Skip)
  - [x] How does REPL generation fit within Spoofax?
- [x] [Requirement analysis](https://github.com/spoofax-shell/doc/pull/17) (Jente)
  - [x] Minimal viable product
- [x] [Frameworks and Tooling](https://github.com/spoofax-shell/doc/pull/8) (Jente)
  - [x] Development frameworks
  - [x] Development tools
- [x] [Conclusion](https://github.com/spoofax-shell/doc/pull/16) (Jente)

**Comment by Unia** [comment]
I think we should update this to hold the questions as sent to Hendrik.

**Comment by Unia** [comment]
Old first post for backup (you can remove this comment if we don't need it)

```
What advantages does literate programming offer?



- What is a REPL?
  - Research functions commonly offered by other REPLs
    - Python
    - R
    - LISP
    - AutoCAD
- What is literate programming?
  - Jupyter notebooks
  - Swift playgrounds
  - Emacs org-mode
  
  
  
  The research report summarizes the results of the research phase of the bachelor project. It should convince the reader that the team has chosen an optimal approach to their problem. Specifically, the relevant alternative solutions should be investigated and compared. All aspects, e.g., choice of algorithms, choice of frameworks, choice of component technology, should be well motivated. The report should include the key references that support the team’s choices. There is no set structure for the report. The team can judge the quality of their own report by asking themselves whether it contains: all the relevant aspects of the project, a sufficient number of references to related work and related systems, and enough material in order to substantiate the major design decisions made in the project. Note that the research report should be included in the final report, cf. “Appendix 2: Guidelines for the Final Report” below. It is instructive to examine reports of past projects in order to understand how to write a useful and comprehensive research report, for example, Ch. 2 of Van Nes, Phan, and Rogalla’s 2014 report and Appendix E of Bijl, van Geest, van der Maarel, Ploegsma’s 2014 report. ​ The team submits the research report to the Coach and the Client. Feedback on the report comes from the Coach. Only in exceptional cases, where there are specific questions, the team can also request feedback on the research report from the Bachelor Coordinators.```

**Comment by gfokkema** [comment]
## Structure of the report

- [ ] Introduction
- [ ] Spoofax (Skip)
	- [ ] SDF (Syntax definition)
	- [ ] NABL (Namespaces)
	- [ ] TS (Types)
	- [ ] DynSem (semantics)
- [ ] REPLs (Jente)
	- [ ] What is a REPL?
	- [ ] How does a REPL fit within Spoofax?
- [ ] Literate Programming?
	- [ ] What is literate programming?
	- [ ] How does literate programming fit within Spoofax?
- [ ] Problem definition
- [ ] Problem analysis
	- [ ] What Spoofax language concepts collide (namespaces, syntax)?
- [ ] Requirement analysis
	- [ ] Minimal viable product
- [ ] Realisation of the product
	- [ ] Methodologies used during the project
	- [ ] Development tools
	- [ ] Available API's from Spoofax
- [ ] Conclusion
Please add your name to whichever section you choose to write.

**Comment by gfokkema** [comment]
## Structure of the report

- [ ] Introduction
- [ ] Spoofax (Skip)
	- [ ] SDF (Syntax definition)
	- [ ] NABL (Namespaces)
	- [ ] TS (Types)
	- [ ] DynSem (semantics)
- [ ] REPLs (Jente)
	- [ ] What is a REPL?
	- [ ] How does a REPL fit within Spoofax?
- [ ] Literate Programming?
	- [ ] What is literate programming?
	- [ ] How does literate programming fit within Spoofax?
- [ ] Problem definition
- [ ] Problem analysis
	- [ ] What Spoofax language concepts collide (namespaces, syntax)?
- [ ] Requirement analysis
	- [ ] Minimal viable product
- [ ] Realisation of the product
	- [ ] Methodologies used during the project
	- [ ] Development tools
	- [ ] Available API's from Spoofax
- [ ] Conclusion
Please add your name to whichever section you choose to write.

**Comment by gfokkema** [comment]
## Structure of the report

- [ ] Introduction
- [ ] Spoofax (Skip)
	- [ ] SDF (Syntax definition)
	- [ ] NABL (Namespaces)
	- [ ] TS (Types)
	- [ ] DynSem (semantics)
- [ ] REPLs (Jente)
	- [ ] What is a REPL?
	- [ ] How does a REPL fit within Spoofax?
- [ ] Literate Programming?
	- [ ] What is literate programming?
	- [ ] How does literate programming fit within Spoofax?
- [ ] Problem definition
- [ ] Problem analysis
	- [ ] What Spoofax language concepts collide (namespaces, syntax)?
- [ ] Requirement analysis
	- [ ] Minimal viable product
- [ ] Realisation of the product
	- [ ] Methodologies used during the project
	- [ ] Development tools
	- [ ] Available API's from Spoofax
- [ ] Conclusion
Please add your name to whichever section you choose to write.

**Comment by gfokkema** [comment]
## Structure of the report

- [ ] Introduction
- [ ] Spoofax (Skip)
	- [ ] SDF (Syntax definition)
	- [ ] NABL (Namespaces)
	- [ ] TS (Types)
	- [ ] DynSem (semantics)
- [ ] REPLs (Jente)
	- [ ] What is a REPL?
	- [ ] How does a REPL fit within Spoofax?
- [ ] Literate Programming?
	- [ ] What is literate programming?
	- [ ] How does literate programming fit within Spoofax?
- [ ] Problem definition
- [ ] Problem analysis
	- [ ] What Spoofax language concepts collide (namespaces, syntax)?
- [ ] Requirement analysis
	- [ ] Minimal viable product
- [ ] Realisation of the product
	- [ ] Methodologies used during the project
	- [ ] Development tools
	- [ ] Available API's from Spoofax
- [ ] Conclusion
Please add your name to whichever section you choose to write.

**Comment by Hjdskes** [comment]
1. ~~Perhaps we should merge the methodologies and tooling subsections, because e.g. we use pull-based development (a methodology) but to facilitate this, we (need to?) use git & GitHub. If we merge these subsections, all of this can be discussed at once.~~
   Methodologies do not have to be discussed.
2. ~~Perhaps we should move the "Available APIs from Spoofax" subsection up into the "Problem Analysis" section or the "How does a REPL fit within Spoofax?" subsection.~~ Moved under the "How does a REPL fit within Spoofax" subsection.

**Comment by Hjdskes** [comment]
Question for @hendrikvanantwerpen:

We're not sure if the section on methodologies and tooling is required in the research report. Can you give your opinion on this?

**Comment by Hjdskes** [comment]
To answer my own question after having asked Hendrik in person: the section on methodologies can be removed, but we should mention the frameworks and tooling. The structure has been updated.

**Comment by Hjdskes** [comment]
Closing, as per #43 everything is now added.
