### ISSUE TITLE
Rewrite global introduction (remove duplication)

### ISSUE THREAD

**Issue by gfokkema** [spoofax-shell/doc#34]
collapsed [issue](https://github.com/spoofax-shell/doc/pull/29#discussion-diff-61857050):

https://github.com/spoofax-shell/doc/pull/29/files?diff=unified#diff-46616cb4ff01a4543eaf70e1a9eb457fR14
https://github.com/spoofax-shell/doc/pull/29/files?diff=unified#diff-46616cb4ff01a4543eaf70e1a9eb457fR28

**Comment by Hjdskes** [comment]
See https://github.com/spoofax-shell/doc/pull/29#discussion_r61867273.
