### ISSUE TITLE
Final report structure

### ISSUE THREAD

**Issue by gfokkema** [spoofax-shell/doc#44]
- [x] Titlesheet
- [x] Preface
- [x] Summary
- [x] Table of Contents
- [x] Introduction
- [x] Background
  - [x] The Spoofax Language Workbench
  - [x] Read-Eval-Print-Loops
  - [x] Literate programming
- [x] Problem Definition and Analysis
  - [x] Problem Definition
  - [x] Problem Analysis
  - [x] Requirements analysis
- [x] Design
  - [x] Overall design (global UML)
  - [x] Command pattern (detailed UML)
  - [x] Function composition (detailed UML)
  - [x] Visitor pattern (detailed UML)
  - [x] Evaluation strategies (detailed UML)
- [x] Implementation
  - [x] Perhaps: backend implementation
  - [x] DynSem Envaluation strategy
    - [x] Dynsem Shell requirements (which rules does the shell need?)
  - [x] ESV extensions
  - [x] Guice
  - [x] Frontends
    - [x] Console
    - [x] Eclipse
- [x] Evaluation
  - [x] Product Evaluation
    - [x] Evaluation of Requirements
    - [x] Evaluation of Design Goals
    - [x] Evaluation of the Product
  - [x] Process Evaluation
    - [x] Development methodologies
    - [x] First SIG feedback
- [x] Discussion
  - [x] Wrapping
  - [x] Dynsem refactoring
  - [x] Eclipse multithreading issues
  - [x] Language interpreters have to be on the classpath
  - [x] Textual representation of DynSem data types
- [x] Recommendations
  - [x] Extending the functionality of the REPL
    - [x] Extending the history functionality
    - [x] Analysis in context
    - [x] Adding support for alternative evaluation strategies
  - [x] Improvements to the Eclipse frontend
  - [x] IPython kernel
- [x] Conclusion
- [x] Bibliography
- [x] Appendix
  - [x] Infosheet
    - **NB:** attach both in appendix and as separate file to the email
  - [x] Project Description
  - [x] Research report
  - [x] Complete UML

**Comment by Hjdskes** [comment]
Hendrik's feedback so that we can find it easily:

> - Problem definition currently has a vague structure. I expect
>   the problem definition after paragraph two. But then you zoom
>   in too quickly, talking about services etc. Also a phrase
>   '... the REPL should ...' is not a problem, but a
>   requirement. A problem is e.g. 'How can we allow ...', or 'What
>   is an easy way to ...', something like that. So what is the
>   problem that you are trying to solve, in one sentence? Then you
>   can expand by listing sub problems, e.g. re-using existing
>   editor services, or supporting different interpreters.
> - In final report, be more clear about 'work with all languages',
>   since this can be interpreted as 'work without extra effort
>   ...'.
> - Some advice for the final report:
>   - Use more pictures, e.g. the sections about execution models
>     (2.3 and 5.1) will be much more clear if you can visualize
>     it.
>   - The structure of scientific text is usually as follows:
>     1. General statement, problem, question.
>     2. Go into details about (1)
>     3. General conclusion, summary, solution.
>        This structure appears on every level, so from chapters to
>        paragraphs. Thinking about (1) and (3) usually helps to
>        determine if all the details in (2) actually belong there.
>   - I think it would be nice if you could explain, with an
>     accompanying figure, the relation between the following:
>     1. Language aspects: Syntax, Static semantics, Dynamic semantics.
>     2. Language specification: Grammar, Typing rules, DynSem rules.
>     3. Input/outputs: Source file, AST, type information,
>        computed value.
>        If you do this for the 'normal' Spoofax case -- and probably
>        you want to be more detailed about the DynSem part -- and
>        also for a generic REPL, then you can show how you connect
>        these two models in the design you have made.
>   - When presenting your design, explain why you think this is
>     general enough, i.e. why could it work for many languages,
>     why could it work for different interpreters, where is it
>     extensible? Showing how it is possible to connect a REPL
>     state that can be extended, with the top-down environment
>     used in expression rules is probably a good case.
> - The outline you sent me is okay, but generic. You should add
>   sections, which show the specifics that you plan to discuss in
>   each chapter.
