### ISSUE TITLE
Let the examples of chapter 2 be around one theme

### ISSUE THREAD

**Issue by Balletie** [spoofax-shell/doc#52]
Currently each subsection uses a different part of the language to explain that specification step. If the examples are about a single theme, e.g. the "if" statement (bad example), then it's easier for the reader.

**Comment by Hjdskes** [comment]
I think comparing two `Bool` classes (e.g. `True` and `False` derived classes, as the lecture with Pharo showed) could work: You can illustrate classes as you currently do in TS/NaBL and you can keep the comparison you have for the DynSem section.

**Comment by Balletie** [comment]
But those are constructs defined in the language itself. We need an example for the specification of classes, not an example for classes.

If i understand you correctly

**Comment by Hjdskes** [comment]
Is this now resolved in #70?

**Comment by Balletie** [comment]
Yes, this can go as there is just an example for dynsem
