### ISSUE TITLE
Add images for execution pipeline, and refer to it

### ISSUE THREAD

**Issue by Balletie** [spoofax-shell/doc#53]
We should have one image for the Spoofax section, where the general pipeline is discussed. Then in the ordered list in the intro we can refer to the image.

In the REPL section add the same image, but updated for the execution pipeline of a REPL (propagation of environment).

**Comment by Unia** [comment]
I think comparing two `Bool` classes (e.g. `True` and `False` derived classes, as the lecture with Pharo showed) could work: You can illustrate classes as you currently do in TS/NaBL and you can keep the comparison you have for the DynSem section.

**Comment by Hjdskes** [comment]
@Balletie This is resolved in #70, isn't it?

**Comment by Balletie** [comment]
Yes, partly. The REPL section should also get one.

**Comment by Balletie** [comment]
Resolved in #70.
