### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by gfokkema** [spoofax-shell/doc#6]
Please note that while this repository is public, at the moment no
contributions from outside contributors are accepted. This project
is a TU Delft course project (TI3806) and the course rules disallow
this. As such, for now this documents merely acts as an internal set
of guidelines.
## Submitting contributions
- Make it clear in the issue tracker what you are working on.
- Keep the [sprint backlog](https://trello.com/b/u2aKQ12y/bachelor-project-spoofax-repl) up to date.
- Be descriptive in your pull request description: what is it for, why
  is it done this way, etc, or which user story.
- Do **_not**_ make cosmetic changes to unrelated files or sections in the same pull
  request. This creates noise, making reviews harder to do.
### Tagging in the issue tracker

When submitting pull requests (commonly referred to as "PRs"), include
one of the following tags prepended to the title:
- `[WIP]` - Work In Progress: the PR will change, so while there is no
  immediate need for review, the submitter still might appreciate it.
- `[RFC]` - Request For Comment: the PR needs reviewing and/or comments.
- `[RDY]` - Ready: the PR has been reviewed by at least one other person and
  has no outstanding issues.

Please keep your tags up to date.
### Branching & history
- Do **_not**_ work on your PR on the master branch, [use a feature branch
  instead](https://www.atlassian.com/git/tutorials/comparing-workflows).
- [Rebase your feature branch onto](http://git-scm.com/book/en/v2/Git-Branching-Rebasing) (upstream) master before
  opening the PR.
- Keep up to date with changes in (upstream) master so your PR is easy to
  merge.
- [Try to actively tidy your history](http://git-scm.com/book/en/v2/Git-Tools-Rewriting-History): combine related
  commits with interactive rebasing, separate monolithic commits, etc. If your
  PR is still `[WIP]`, feel free to force-push to your feature branch to tidy
  your history. Please read [how to use rebase](http://git-scm.com/book/en/v2/Git-Branching-Rebasing), to see how to
  squash or otherwise edit your commits.
### For code pull requests

Before making a pull request, please rebase on upstream master (see above) and
provide a clean history (see above). Please also make sure to run `mvn test`,
to see if there are any outstanding issues (Checkstyle (see below), PMD, FindBugs, etc).
#### Testing

All PRs are expected to have (unit) tests to go with them. If no tests
are provided, PRs will not be merged unless there is a viable reason.
PRs will also not be merged if the Travis continuous integration build fails.
#### Coding style

For new code, run Checkstyle to detect style errors. It's not perfect,
so some warnings may be false positives/negatives. Maven is set up to
fail on every style error. Should Checkstyle report too much false
positives/negatives, please edit Checkstyle's [configuration](https://github.com/DNAinator/dnainator/blob/master/checkstyle.xml). To have Checkstyle
ignore certain cases, see [this](http://stackoverflow.com/questions/4023185/how-to-disable-a-particular-checkstyle-rule-for-a-particular-line-of-code) stackoverflow question.
### Commit guidelines

The purpose of these guidelines is to _make reviews easier_ and make
the history logs more valuable.
- Try to keep the first line under 72 characters.
- If necessary, include further description after a blank line.
  - Don't make the description too verbose by including obvious things, but
    don't spare clarifications for anything that may be not so obvious.
    Some commit messages are pages long, and that's fine if there's no
    better place for those comments to live.
  - **Recommended:** Prefix logically-related commits with a consistent
    identifier in each commit message. For already used identifiers, see the
    commit history for the respective file(s) you're editing.
    For example: `<ClassName>: fix all the issues`
- Use the [imperative voice](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html): "Fix bug" rather than "Fixed bug" or "Fixes bug."
### Reviewing pull requests

You may find it easier to instead use an interactive program for code reviews,
such as [`tig`](https://github.com/jonas/tig).

<sup>Kindly taken and modified from [neovim](http://neovim.io/).</sup>

**Comment by Hjdskes** [comment]
Closed as this file now exist in our source code repository: [CONTRIBUTING.md](https://github.com/spoofax-shell/spoofax-shell/blob/master/CONTRIBUTING.md).
