### ISSUE TITLE
Happy accidents to reference in discussion

### ISSUE THREAD

**Issue by Balletie** [spoofax-shell/doc#60]
I call them happy accidents instead of mistakes.

List:
- [x] Our early approaches with "wrapping"
- [ ] Generating REPLs
- [ ] Earlier design decisions
  - [x] Single-threaded nature of the architecture and clash with multi-threaded nature of Eclipse plugin
  - [ ] Child commands and their inflexibility

**Comment by Hjdskes** [comment]
Blocking vs. non-blocking input is another one you can add.

**Comment by Balletie** [comment]
does that not fall under "single-threaded vs multi-threaded"?

**Comment by Hjdskes** [comment]
Do we have to discuss the ones that are currently not checked off? Personally I don't think so.

**Comment by Balletie** [comment]
I agree, we can leave them.
